baseURL = 'https://repinger.my.id/'
languageCode = 'en-us'
title = 'repinger'
theme = "terminal"

[minify]
	minifyOutput = true

[params]
	centerTheme = true
	favicon = "favicon.png"
	themeColor = "orange"

[languages]
	[languages.en]
		copyright = "© 2023"
		[languages.en.params.logo]
			logoText = "repinger"
